name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congrats on making your first issue and thanks for taking the time to improve SpeakEd ! 🎉 ✨ 😊'
        pr-message: 'Congrats on making your first Pull Request and thanks for taking the time to improve SpeakEd ! 🎉 ✨ 😊'
        
